### ISSUE TITLE
SIARD 2.0

### ISSUE THREAD

**Issue by akuckartz** [KOST-CECO/KOST-Val#36]
Please support SIARD 2.0 validation.

**Comment by Chlara** [comment]
in KOST-Val erledigt: 215a1bc3d643dfc82ddf7b797fa913022042daa8
seitens eCH eingereicht aber noch offen

**Comment by stighemmer** [comment]
If I understand the German text correctly, you say that this was added in 1.8.1.
But... I see this issue is still listed as open.  Why?
(I suppose the second sentence explains this, but  I don't understand it)

The reason I ask is that I have a file that is supposed to be Siard-2, but doesn't validate.  This might be a problem with the file, OR it might be a problem with KOST-Val.  I am trying to find out which.

I have tested with both versions 1.8.3 and 1.9.0.  In both cases I get the message "D Unknown Error" which is not very helpful.

I have also consulted DROID, which recognizes the file as Siard 2.0, but I assume that it is testing much less than KOST-Val does.

Here are links to the [log file from 1.9.0](https://drive.google.com/open?id=1Fwyh13MqwQtS6Eovk3oYz4xbxs-FTfcH). and [the SIARD file](https://drive.google.com/open?id=1g_XMaeVEelnEfREybumbnGKPY5R7I_oU) that causes it.
