### ISSUE TITLE
SIARD 2.1

### ISSUE THREAD

**Issue by marhop** [KOST-CECO/KOST-Val#48]
Hello,

Is validation of SIARD 2.1 supported? Trying to validate a SIARD 2.1 file with KOST-Val 1.9.1, I got this error:

> header validation | An unknown error has occurred. invalid size (expected from local header/data descriptor 0 but actually found 15703 bytes)

However, this could also be caused by the outdated ZIP64 library you are using. Would you consider switching from 1.0 to the current 2.1? There have been some bugfixes in the lib that remind me of the KOST-Val error cited above ... See <https://github.com/sfa-siard/Zip64File/releases>.

Thanks,
Martin

**Comment by Chlara** [comment]
Hallo Martin

Danke für die Issue, welche ich auch seitens BAR erhalten habe.
Könntest du https://github.com/KOST-CECO/KOST-Val/releases/tag/1.9.2_beta testen?

Liebi Grüessli   Claire

**Comment by marhop** [comment]
Hallo Claire,

habe es getestet, diesmal gibt es diesen Fehler:

> A) readability | The SIARD file could not be opened properly: invalid entry size (expected 0 but got 15703 bytes). -> Validation aborted!

Viele Grüße
Martin

**Comment by Chlara** [comment]
Anstelle die veraltete Version von Zip64File v1.0 upzudaten habe ich beschlossen eine unabhängige Implementierung zu verwenden. Damit können Fehler in der Implementierung besser festgestellt werden.
Java.util.zip kann grundsätzlich ZIP-64 öffnen, nur nicht die jenigen welche mit der Version 2.1 von Zip64File erstellt wurden.
Es wird ein ähnlicher Fehler gemeldet wie die alte Version 1.0.

**Da ich der Meinung bin, dass es immer gut ist auch unabhängige Tools einsetzten zu können, muss es in der Community entschieden werden, ob dies ein Issue in KOST-Val respektive java.util.zip oder SIARD Suite respektive Zip64File (https://github.com/sfa-siard/Zip64File) ist.**

-----

Instead of updating the outdated version of Zip64File v1.0, I decided to use an independent implementation.
Java.util.zip can basically open ZIP-64, but not those created with version 2.1 of Zip64File.
A similar bug is reported as the old version 1.0.

**I have the opinion that it is always good to be able to use independent tools. It has to be decided in the community whether this is an issue in KOST-Val respectivly java.util.zip or SIARD Suite respectively Zip64File (https://github.com/sfa-siard/Zip64File).**

**Comment by Chlara** [comment]
Seit 1.9.5 behoben 
65a81fbc9ba6c6b89bf92a0a1ba453055cab9311
